name: ChangelogUpdated

on:
  workflow_call:


jobs:
  build:
    name: Check for new news fragments
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install
        run: |
          $CONDA/bin/conda install -c lsstts -c conda-forge pre-commit ts-pre-commit-config python=3.11 -y
          $CONDA/bin/conda install -c conda-forge towncrier=23 -y
          $CONDA/bin/generate_pre_commit_conf --skip-pre-commit-install
  
      - name: Run towncrier check command
        run: |
          $CONDA/bin/towncrier check --compare-with origin/develop --config towncrier.toml

